using Wolfgang.Conflict.Nes.Engine.Map;
using Wolfgang.Conflict.Nes.Engine.Units;

namespace Wolfgang.Conflict.Nes.Engine.Rules;

/// <summary>
/// Pure functions for the manual's F.P. (Fame Point) economy rules.
/// </summary>
public static class EconomyRules
{
    /// <summary>
    /// Per-turn income generated by an owned building. Only Cities and
    /// Airbases produce income; HQ, Factory and Port produce nothing.
    /// </summary>
    public static int BuildingIncomePerTurn(BuildingKind building) => building switch
    {
        BuildingKind.City => 100,
        BuildingKind.Airbase => 100,
        _ => 0,
    };

    /// <summary>
    /// F.P. lost by the side that just lost a unit in combat. Equal to half
    /// the destroyed unit's production cost (rounded down).
    /// </summary>
    /// <param name="destroyedUnitProductionCost">The destroyed unit's F.P. production cost.</param>
    public static int LoserPenalty(int destroyedUnitProductionCost)
        => destroyedUnitProductionCost / 2;

    /// <summary>
    /// F.P. awarded to the side that destroyed an enemy unit, based on the
    /// matchup outlook from the winner's perspective <i>before</i> combat.
    /// </summary>
    /// <param name="winnerOutlook">
    /// The pre-combat tier from the winner's perspective. The bigger the
    /// upset (winner was expected to lose), the larger the bounty.
    /// </param>
    public static int WinnerReward(MatchupTier winnerOutlook) => winnerOutlook switch
    {
        MatchupTier.CompleteDefeat => 900,
        MatchupTier.AtDisadvantage => 600,
        MatchupTier.Equal or MatchupTier.AtAdvantage or MatchupTier.TotalVictory => 300,
        _ => 300,
    };
}
